### ISSUE TITLE
lua-orm如何应用

### ISSUE THREAD

**Issue by wesom** [pigparadise/lua-orm#1]
1.参考test_cost.lua，实际项目设计中，生成的obj_*是否作为内存数据库的项值供检索？
2.在业务逻辑层，如果在obj_*的基础上封装，比如  bag = { data = obj_a, ... methods ...},当field有变化时，怎么设计对应的变化输出，比如增删改查？DSL能否设计的更完善，将这些需求体现出来？

**Comment by pigparadise** [comment]
不好意思，才看到... 想起后面我们发过邮件
